from . import auth
from . import profile
from . import contact_us
from . import get_data
from . import add_rate
from . import section_quize
from . import LMS
from . import verfiy_token
from . import work_papers