from . import res_user_inherit
from . import course_video
from . import res_country_state
from . import token
from . import verification
from . import courses
from . import section
from . import teacher
from . import contact_us
from . import about_us
from . import daily_article
from . import why_us
from . import rate
from . import teacher_rate
from . import skills
from . import results
from . import course_result
from . import video_quiz
from . import privacy_policy
from . import subscribtion
from . import payment_type
from . import section_result
from . import denouncement
from . import notifications
from . import send_notification_all_user
from . import conversation
from . import hero_section
from .import fqa
from .import student_class
from .import refrences
from . import devices
from . import user_courses_status
from . import promoters
from . import our_partners
from . import subscription_payments
from . import packages
from . import package_subscribtion_payment
from . import platform_control
from . import educational_supervisor
from . import subscribe_quiz
from . import work_papers