{
    'name': 'Taleb',
    'summary': '',
    'description': " ",
    'author': 'Ali Ammar',
    'website': 'aliammarfin@gmail.com , +963937214143',

    # category can be used to filter modules in modules listing
    'category': 'test',
    'version': '0.1',

    # any module for this one to work correctly
    'depends': ['base', 'mail','web'],
    'assets': {
    'web.assets_backend': [
        'taleb/static/src/js/delete_comment_alert.js',
    ]
},
    # always loaded
    'data': [
        'security/res_groups.xml',
            'security/ir.model.access.csv',
            'data/cron.xml',
            'data/schedual_action_valid_code.xml',
            'data/demo_data.xml',
            'views/res_user_inherit.xml',
            'views/res_state_inherite.xml',
            'views/user_token.xml',
            'views/user_verification.xml',
            'views/contact_us.xml',
            'views/about_us.xml',
            'views/teacher_view.xml',
            'views/daily_article.xml',
            'views/course_video.xml',
            'views/why_us_view.xml',
            'views/rate.xml',
            'views/resault.xml',
            'views/teacher_rate.xml',
            'views/course_view.xml',
            'views/privacy_policy.xml',
            'views/subscription.xml',
            'views/enquiries.xml',
            'views/section_quize.xml',
            'views/payment_type.xml',
            'views/points.xml',
            'views/points_subscriptions.xml',
            'views/section_quize_result.xml',
            'views/payment_type.xml',
            'views/denouncement.xml',
            # 'views/supervisor.xml',
            'views/delete_comment.xml',
            'views/notification.xml',
            'views/points_user.xml',
            'views/send_notification_all_user.xml',
            'views/conversation.xml',   
            'views/message.xml',
            'views/hero_section_view.xml',
            'views/promoter.xml',
            'views/send_notification_all_user.xml',
            'views/fqa.xml',
            'views/refrences.xml',
            'views/send_notification_all_user.xml',
            'views/session_status.xml',
            'views/course_status.xml',
            'views/section_status.xml',
            'views/devices.xml',
            'views/our_partner.xml',
            'views/block_student.xml',
            'views/rate_video.xml',
            'views/configration_point.xml',
            'views/payment_tracker.xml',
            'views/subtract_user.xml',
            'views/Packages.xml',
            'views/package_tracker.xml',
            # 'views/location_state.xml',
            'views/term_of_use.xml',
            'wizard/report_action.xml',
            'wizard/report_template.xml',
            'wizard/coupon_wizard_form.xml',
            'views/platform_control.xml',
            'views/student_class.xml',
            'views/work_papers.xml',
            'views/work_papers_comments.xml',
            'views/quiz_subscribe.xml',
            
    ],


    # loaded in demo mode only
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
     }
