from . import student_report
from . import student_mood
from . import student_drinks
from . import student_health
from . import behavior
from . import temperature
from . import album
from . import gallary
from . import events
from . import year_class
from . import year
from . import meals
from . import res_user_inherit
from . import home_work
from . import subjects
from . import notifications
from . import messages
from . import user_token
# from . import product_template